{
  "openapi": "3.0.0",
  "info": {
    "title": "poetassistant",
    "version": "1.0.0",
    "license": {
      "name": "GPL-3.0"
    },
    "description": "Specification JSONs: [v2](/api-spec/v2), [v3](/api-spec/v3).\n\nREST API for English-language tools for writing poetry"
  },
  "paths": {
    "/rhymes": {
      "get": {
        "summary": "/rhymes",
        "parameters": [
          {
            "name": "word",
            "in": "query",
            "example": "dove",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "example": "2",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "size",
            "in": "query",
            "example": "10",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/html": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "next": {
                      "type": "string",
                      "example": "http://localhost:3000/rhymes?word=dove&page=3&size=10"
                    },
                    "previous": {
                      "type": "string",
                      "example": "http://localhost:3000/rhymes?word=dove&page=1&size=10"
                    },
                    "count": {
                      "type": "number",
                      "example": 10
                    },
                    "results": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "syllables_type": {
                            "type": "string"
                          },
                          "syllables": {
                            "type": "string"
                          },
                          "word": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "syllables_type",
                          "syllables",
                          "word"
                        ]
                      },
                      "example": [
                        {
                          "syllables_type": "stress_syllables",
                          "syllables": "OWV",
                          "word": "nov"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "tags": []
      }
    },
    "/thesaurus": {
      "get": {
        "summary": "/thesaurus",
        "parameters": [
          {
            "name": "word",
            "in": "query",
            "example": "hell",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "example": "1",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "size",
            "in": "query",
            "example": "10",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/html": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "count": {
                      "type": "number",
                      "example": 6
                    },
                    "results": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "part_of_speech": {
                            "type": "string"
                          },
                          "synonyms": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          },
                          "antonyms": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          }
                        },
                        "required": [
                          "part_of_speech",
                          "synonyms",
                          "antonyms"
                        ]
                      },
                      "example": [
                        {
                          "part_of_speech": "noun",
                          "synonyms": [
                            "hell on earth",
                            "hellhole",
                            "inferno",
                            "part",
                            "region",
                            "snake pit",
                            "the pits"
                          ],
                          "antonyms": []
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "tags": []
      }
    },
    "/definitions": {
      "get": {
        "summary": "/definitions",
        "parameters": [
          {
            "name": "word",
            "in": "query",
            "example": "baffled",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "example": "1",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "size",
            "in": "query",
            "example": "10",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/html": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "count": {
                      "type": "number",
                      "example": 2
                    },
                    "results": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "part_of_speech": {
                            "type": "string"
                          },
                          "definition": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "part_of_speech",
                          "definition"
                        ]
                      },
                      "example": [
                        {
                          "part_of_speech": "adjective",
                          "definition": "perplexed by many conflicting situations or statements; filled with bewilderment"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "tags": []
      }
    },
    "/wotd": {
      "get": {
        "summary": "/wotd",
        "parameters": [
          {
            "name": "before",
            "in": "query",
            "example": "2022-03-10",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "size",
            "in": "query",
            "example": "14",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/html": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "date": {
                        "type": "string"
                      },
                      "word": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "date",
                      "word"
                    ]
                  }
                }
              }
            }
          }
        },
        "tags": []
      }
    }
  },
  "tags": [],
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ]
}